# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui-lite.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 650)
        MainWindow.setMinimumSize(QtCore.QSize(750, 650))
        MainWindow.setMaximumSize(QtCore.QSize(750, 650))
        MainWindow.setStyleSheet("background-color:rgb(22, 35, 51)")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.paginador = QtWidgets.QStackedWidget(self.centralwidget)
        self.paginador.setObjectName("paginador")
        self.polos_salientes = QtWidgets.QWidget()
        self.polos_salientes.setObjectName("polos_salientes")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.polos_salientes)
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.cont_saliente = QtWidgets.QFrame(self.polos_salientes)
        self.cont_saliente.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cont_saliente.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cont_saliente.setObjectName("cont_saliente")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.cont_saliente)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(10)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.saliente_titulo_1 = QtWidgets.QLabel(self.cont_saliente)
        self.saliente_titulo_1.setMinimumSize(QtCore.QSize(0, 30))
        self.saliente_titulo_1.setMaximumSize(QtCore.QSize(16777215, 60))
        self.saliente_titulo_1.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 24px;\n"
"}")
        self.saliente_titulo_1.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.saliente_titulo_1.setObjectName("saliente_titulo_1")
        self.verticalLayout_12.addWidget(self.saliente_titulo_1)
        self.saliente_titulo = QtWidgets.QLabel(self.cont_saliente)
        self.saliente_titulo.setMinimumSize(QtCore.QSize(0, 30))
        self.saliente_titulo.setMaximumSize(QtCore.QSize(16777215, 35))
        self.saliente_titulo.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"font-size: 16px;\n"
"}")
        self.saliente_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.saliente_titulo.setObjectName("saliente_titulo")
        self.verticalLayout_12.addWidget(self.saliente_titulo)
        self.saliente_inputs = QtWidgets.QFrame(self.cont_saliente)
        self.saliente_inputs.setStyleSheet("")
        self.saliente_inputs.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.saliente_inputs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.saliente_inputs.setObjectName("saliente_inputs")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.saliente_inputs)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.saliente_input_content = QtWidgets.QFrame(self.saliente_inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saliente_input_content.sizePolicy().hasHeightForWidth())
        self.saliente_input_content.setSizePolicy(sizePolicy)
        self.saliente_input_content.setMinimumSize(QtCore.QSize(700, 350))
        self.saliente_input_content.setMaximumSize(QtCore.QSize(900, 420))
        self.saliente_input_content.setStyleSheet("QFrame{\n"
"background-color: rgb(217, 217, 217);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: black;\n"
"border-width: 2px;\n"
"}")
        self.saliente_input_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.saliente_input_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.saliente_input_content.setObjectName("saliente_input_content")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.saliente_input_content)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.input_left_sal = QtWidgets.QFrame(self.saliente_input_content)
        self.input_left_sal.setStyleSheet("QFrame{\n"
"background-color: rgb(217, 217, 217);\n"
"border-style: none;\n"
"}")
        self.input_left_sal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_left_sal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_left_sal.setObjectName("input_left_sal")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.input_left_sal)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_22 = QtWidgets.QFrame(self.input_left_sal)
        self.frame_22.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.sal_p_aparente = QtWidgets.QLineEdit(self.frame_22)
        self.sal_p_aparente.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sal_p_aparente.setStyleSheet("QLineEdit{\n"
"background-color: rgb(243, 238, 238);\n"
"border-radius: 2px;\n"
"border: 1px solid gray;\n"
"}")
        self.sal_p_aparente.setObjectName("sal_p_aparente")
        self.horizontalLayout_16.addWidget(self.sal_p_aparente)
        self.sal_p_aparente_label = QtWidgets.QLabel(self.frame_22)
        self.sal_p_aparente_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sal_p_aparente_label.setStyleSheet("QLabel{\n"
"color: rgb(53, 53, 53);\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"}")
        self.sal_p_aparente_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sal_p_aparente_label.setObjectName("sal_p_aparente_label")
        self.horizontalLayout_16.addWidget(self.sal_p_aparente_label)
        self.verticalLayout_13.addWidget(self.frame_22)
        self.frame_24 = QtWidgets.QFrame(self.input_left_sal)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.sal_f_p = QtWidgets.QLineEdit(self.frame_24)
        self.sal_f_p.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sal_f_p.setStyleSheet("QLineEdit{\n"
"background-color: rgb(243, 238, 238);\n"
"border-radius: 2px;\n"
"border: 1px solid gray;\n"
"}")
        self.sal_f_p.setObjectName("sal_f_p")
        self.horizontalLayout_18.addWidget(self.sal_f_p)
        self.sal_f_p_label = QtWidgets.QLabel(self.frame_24)
        self.sal_f_p_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sal_f_p_label.setStyleSheet("QLabel{\n"
"color: rgb(53, 53, 53);\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"}")
        self.sal_f_p_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sal_f_p_label.setObjectName("sal_f_p_label")
        self.horizontalLayout_18.addWidget(self.sal_f_p_label)
        self.verticalLayout_13.addWidget(self.frame_24)
        self.frame_25 = QtWidgets.QFrame(self.input_left_sal)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.sal_t_m_c = QtWidgets.QLineEdit(self.frame_25)
        self.sal_t_m_c.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sal_t_m_c.setStyleSheet("QLineEdit{\n"
"background-color: rgb(243, 238, 238);\n"
"border-radius: 2px;\n"
"border: 1px solid gray;\n"
"}")
        self.sal_t_m_c.setObjectName("sal_t_m_c")
        self.horizontalLayout_19.addWidget(self.sal_t_m_c)
        self.sal_t_m_c_label = QtWidgets.QLabel(self.frame_25)
        self.sal_t_m_c_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sal_t_m_c_label.setStyleSheet("QLabel{\n"
"color: rgb(53, 53, 53);\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"}")
        self.sal_t_m_c_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sal_t_m_c_label.setObjectName("sal_t_m_c_label")
        self.horizontalLayout_19.addWidget(self.sal_t_m_c_label)
        self.verticalLayout_13.addWidget(self.frame_25)
        self.frame_26 = QtWidgets.QFrame(self.input_left_sal)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.sal_estabilidad_practica = QtWidgets.QLineEdit(self.frame_26)
        self.sal_estabilidad_practica.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sal_estabilidad_practica.setStyleSheet("QLineEdit{\n"
"background-color: rgb(243, 238, 238);\n"
"border-radius: 2px;\n"
"border: 1px solid gray;\n"
"}")
        self.sal_estabilidad_practica.setObjectName("sal_estabilidad_practica")
        self.horizontalLayout_20.addWidget(self.sal_estabilidad_practica)
        self.sal_estabilidad_practica_label = QtWidgets.QLabel(self.frame_26)
        self.sal_estabilidad_practica_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sal_estabilidad_practica_label.setStyleSheet("QLabel{\n"
"color: rgb(53, 53, 53);\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"}")
        self.sal_estabilidad_practica_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sal_estabilidad_practica_label.setObjectName("sal_estabilidad_practica_label")
        self.horizontalLayout_20.addWidget(self.sal_estabilidad_practica_label)
        self.verticalLayout_13.addWidget(self.frame_26)
        self.saliente_pu_check = QtWidgets.QCheckBox(self.input_left_sal)
        self.saliente_pu_check.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.saliente_pu_check.setStyleSheet("QCheckBox{\n"
"background-color: rgb(217, 217, 217);\n"
"color: rgb(53, 53, 53);\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"}")
        self.saliente_pu_check.setObjectName("saliente_pu_check")
        self.verticalLayout_13.addWidget(self.saliente_pu_check)
        self.horizontalLayout_10.addWidget(self.input_left_sal)
        self.input_right_sal = QtWidgets.QFrame(self.saliente_input_content)
        self.input_right_sal.setStyleSheet("QFrame{\n"
"background-color: rgb(217, 217, 217);\n"
"border-style: none;\n"
"}")
        self.input_right_sal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_right_sal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_right_sal.setObjectName("input_right_sal")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.input_right_sal)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.cont_r_q_sal = QtWidgets.QFrame(self.input_right_sal)
        self.cont_r_q_sal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cont_r_q_sal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cont_r_q_sal.setObjectName("cont_r_q_sal")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.cont_r_q_sal)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.sal_r_q = QtWidgets.QLineEdit(self.cont_r_q_sal)
        self.sal_r_q.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sal_r_q.setStyleSheet("QLineEdit{\n"
"background-color: rgb(243, 238, 238);\n"
"border-radius: 2px;\n"
"border: 1px solid gray;\n"
"}")
        self.sal_r_q.setObjectName("sal_r_q")
        self.horizontalLayout_26.addWidget(self.sal_r_q)
        self.sal_r_q_label = QtWidgets.QLabel(self.cont_r_q_sal)
        self.sal_r_q_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sal_r_q_label.setStyleSheet("QLabel{\n"
"color: rgb(53, 53, 53);\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"}")
        self.sal_r_q_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sal_r_q_label.setObjectName("sal_r_q_label")
        self.horizontalLayout_26.addWidget(self.sal_r_q_label)
        self.verticalLayout_14.addWidget(self.cont_r_q_sal)
        self.cont_voltaje_nom_sal = QtWidgets.QFrame(self.input_right_sal)
        self.cont_voltaje_nom_sal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cont_voltaje_nom_sal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cont_voltaje_nom_sal.setObjectName("cont_voltaje_nom_sal")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.cont_voltaje_nom_sal)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.voltaje_nominal_sal = QtWidgets.QComboBox(self.cont_voltaje_nom_sal)
        self.voltaje_nominal_sal.setMinimumSize(QtCore.QSize(101, 0))
        self.voltaje_nominal_sal.setMaximumSize(QtCore.QSize(100, 16777215))
        self.voltaje_nominal_sal.setStyleSheet("QComboBox{\n"
"background-color: rgb(243, 238, 238);\n"
"border: 1px solid gray;\n"
"border-radius: 3px;\n"
"padding: 1px 18px 1px 3px;\n"
"min-width: 6em;\n"
"}\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"QScrollBar:vertical {          \n"
"    border-style: solid;\n"
"    background: rgb(243, 238, 238);\n"
"    width:15px;\n"
"}\n"
"")
        self.voltaje_nominal_sal.setObjectName("voltaje_nominal_sal")
        self.voltaje_nominal_sal.addItem("")
        self.voltaje_nominal_sal.addItem("")
        self.voltaje_nominal_sal.addItem("")
        self.voltaje_nominal_sal.addItem("")
        self.voltaje_nominal_sal.addItem("")
        self.voltaje_nominal_sal.addItem("")
        self.voltaje_nominal_sal.addItem("")
        self.voltaje_nominal_sal.addItem("")
        self.voltaje_nominal_sal.addItem("")
        self.voltaje_nominal_sal.addItem("")
        self.voltaje_nominal_sal.addItem("")
        self.voltaje_nominal_sal.addItem("")
        self.horizontalLayout_21.addWidget(self.voltaje_nominal_sal)
        self.sal_v_n_label = QtWidgets.QLabel(self.cont_voltaje_nom_sal)
        self.sal_v_n_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sal_v_n_label.setStyleSheet("QLabel{\n"
"color: rgb(53, 53, 53);\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"}")
        self.sal_v_n_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sal_v_n_label.setObjectName("sal_v_n_label")
        self.horizontalLayout_21.addWidget(self.sal_v_n_label)
        self.verticalLayout_14.addWidget(self.cont_voltaje_nom_sal)
        self.cont_r_d_sal = QtWidgets.QFrame(self.input_right_sal)
        self.cont_r_d_sal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cont_r_d_sal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cont_r_d_sal.setObjectName("cont_r_d_sal")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.cont_r_d_sal)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.sal_r_d = QtWidgets.QLineEdit(self.cont_r_d_sal)
        self.sal_r_d.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sal_r_d.setStyleSheet("QLineEdit{\n"
"background-color: rgb(243, 238, 238);\n"
"border-radius: 2px;\n"
"border: 1px solid gray;\n"
"}")
        self.sal_r_d.setObjectName("sal_r_d")
        self.horizontalLayout_22.addWidget(self.sal_r_d)
        self.sal_r_d_label = QtWidgets.QLabel(self.cont_r_d_sal)
        self.sal_r_d_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sal_r_d_label.setStyleSheet("QLabel{\n"
"color: rgb(53, 53, 53);\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"}")
        self.sal_r_d_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sal_r_d_label.setObjectName("sal_r_d_label")
        self.horizontalLayout_22.addWidget(self.sal_r_d_label)
        self.verticalLayout_14.addWidget(self.cont_r_d_sal)
        self.cont_p_m_sal = QtWidgets.QFrame(self.input_right_sal)
        self.cont_p_m_sal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cont_p_m_sal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cont_p_m_sal.setObjectName("cont_p_m_sal")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.cont_p_m_sal)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.sal_p_m = QtWidgets.QLineEdit(self.cont_p_m_sal)
        self.sal_p_m.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sal_p_m.setStyleSheet("QLineEdit{\n"
"background-color: rgb(243, 238, 238);\n"
"border-radius: 2px;\n"
"border: 1px solid gray;\n"
"}")
        self.sal_p_m.setObjectName("sal_p_m")
        self.horizontalLayout_23.addWidget(self.sal_p_m)
        self.sal_p_m_label = QtWidgets.QLabel(self.cont_p_m_sal)
        self.sal_p_m_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sal_p_m_label.setStyleSheet("QLabel{\n"
"color: rgb(53, 53, 53);\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"}")
        self.sal_p_m_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sal_p_m_label.setObjectName("sal_p_m_label")
        self.horizontalLayout_23.addWidget(self.sal_p_m_label)
        self.verticalLayout_14.addWidget(self.cont_p_m_sal)
        self.cont_seg_max_sal = QtWidgets.QFrame(self.input_right_sal)
        self.cont_seg_max_sal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cont_seg_max_sal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cont_seg_max_sal.setObjectName("cont_seg_max_sal")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.cont_seg_max_sal)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.sal_porcentaje_seg = QtWidgets.QComboBox(self.cont_seg_max_sal)
        self.sal_porcentaje_seg.setMinimumSize(QtCore.QSize(101, 0))
        self.sal_porcentaje_seg.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sal_porcentaje_seg.setStyleSheet("QComboBox{\n"
"background-color: rgb(243, 238, 238);\n"
"border: 1px solid gray;\n"
"border-radius: 3px;\n"
"padding: 1px 18px 1px 3px;\n"
"min-width: 6em;\n"
"}\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"QScrollBar:vertical {          \n"
"    border-style: solid;\n"
"    background: rgb(243, 238, 238);\n"
"    width:15px;\n"
"}")
        self.sal_porcentaje_seg.setObjectName("sal_porcentaje_seg")
        self.sal_porcentaje_seg.addItem("")
        self.sal_porcentaje_seg.addItem("")
        self.sal_porcentaje_seg.addItem("")
        self.sal_porcentaje_seg.addItem("")
        self.sal_porcentaje_seg.addItem("")
        self.horizontalLayout_24.addWidget(self.sal_porcentaje_seg)
        self.sal_porcentaj_seg_label = QtWidgets.QLabel(self.cont_seg_max_sal)
        self.sal_porcentaj_seg_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sal_porcentaj_seg_label.setStyleSheet("QLabel{\n"
"color: rgb(53, 53, 53);\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"}")
        self.sal_porcentaj_seg_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sal_porcentaj_seg_label.setObjectName("sal_porcentaj_seg_label")
        self.horizontalLayout_24.addWidget(self.sal_porcentaj_seg_label)
        self.verticalLayout_14.addWidget(self.cont_seg_max_sal)
        self.horizontalLayout_10.addWidget(self.input_right_sal)
        self.horizontalLayout_9.addWidget(self.saliente_input_content)
        self.verticalLayout_12.addWidget(self.saliente_inputs)
        self.saliente_campos = QtWidgets.QLabel(self.cont_saliente)
        self.saliente_campos.setMinimumSize(QtCore.QSize(0, 30))
        self.saliente_campos.setMaximumSize(QtCore.QSize(16777215, 25))
        self.saliente_campos.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"font-size: 14px;\n"
"}")
        self.saliente_campos.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.saliente_campos.setObjectName("saliente_campos")
        self.verticalLayout_12.addWidget(self.saliente_campos)
        self.saliente_error_mess = QtWidgets.QLabel(self.cont_saliente)
        self.saliente_error_mess.setMinimumSize(QtCore.QSize(0, 30))
        self.saliente_error_mess.setMaximumSize(QtCore.QSize(16777215, 25))
        self.saliente_error_mess.setStyleSheet("QLabel{\n"
"color: red;\n"
"}")
        self.saliente_error_mess.setText("")
        self.saliente_error_mess.setAlignment(QtCore.Qt.AlignCenter)
        self.saliente_error_mess.setObjectName("saliente_error_mess")
        self.verticalLayout_12.addWidget(self.saliente_error_mess)
        self.saliente_content_but = QtWidgets.QFrame(self.cont_saliente)
        self.saliente_content_but.setMinimumSize(QtCore.QSize(0, 50))
        self.saliente_content_but.setMaximumSize(QtCore.QSize(16777215, 50))
        self.saliente_content_but.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.saliente_content_but.setFrameShadow(QtWidgets.QFrame.Raised)
        self.saliente_content_but.setObjectName("saliente_content_but")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.saliente_content_but)
        self.horizontalLayout_25.setContentsMargins(40, 0, 40, 5)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.saliente_graficar = QtWidgets.QPushButton(self.saliente_content_but)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.saliente_graficar.setFont(font)
        self.saliente_graficar.setStyleSheet("QPushButton{\n"
"background-color: rgb(194, 221, 245);\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(143, 163, 188, 245);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-color: beige;\n"
"color: white;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/derecha.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saliente_graficar.setIcon(icon)
        self.saliente_graficar.setIconSize(QtCore.QSize(0, 0))
        self.saliente_graficar.setObjectName("saliente_graficar")
        self.horizontalLayout_25.addWidget(self.saliente_graficar)
        spacerItem = QtWidgets.QSpacerItem(470, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem)
        self.saliente_anterior = QtWidgets.QPushButton(self.saliente_content_but)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.saliente_anterior.setFont(font)
        self.saliente_anterior.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.saliente_anterior.setStyleSheet("QPushButton{\n"
"background-color: rgb(194, 221, 245);\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(143, 163, 188, 245);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-color: beige;\n"
"color: white;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../img/izquierda.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saliente_anterior.setIcon(icon1)
        self.saliente_anterior.setIconSize(QtCore.QSize(0, 0))
        self.saliente_anterior.setObjectName("saliente_anterior")
        self.horizontalLayout_25.addWidget(self.saliente_anterior)
        self.verticalLayout_12.addWidget(self.saliente_content_but)
        self.hboxlayout.addWidget(self.cont_saliente)
        self.paginador.addWidget(self.polos_salientes)
        self.espera = QtWidgets.QWidget()
        self.espera.setObjectName("espera")
        self.layout_espera = QtWidgets.QVBoxLayout(self.espera)
        self.layout_espera.setContentsMargins(0, 0, 0, 0)
        self.layout_espera.setSpacing(0)
        self.layout_espera.setObjectName("layout_espera")
        self.espera_content = QtWidgets.QFrame(self.espera)
        self.espera_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.espera_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espera_content.setObjectName("espera_content")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.espera_content)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem1 = QtWidgets.QSpacerItem(20, 236, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.espera_content)
        self.label_2.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 24px;\n"
"margin-bottom: 50px;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_11.addWidget(self.label_2)
        self.barra_espera = QtWidgets.QProgressBar(self.espera_content)
        self.barra_espera.setMinimumSize(QtCore.QSize(700, 0))
        self.barra_espera.setMaximumSize(QtCore.QSize(850, 15))
        self.barra_espera.setMouseTracking(False)
        self.barra_espera.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.barra_espera.setAutoFillBackground(False)
        self.barra_espera.setStyleSheet("QProgressBar{\n"
"border: 1px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"background-color: rgb(103, 161, 255);\n"
"}\n"
"")
        self.barra_espera.setProperty("value", 50)
        self.barra_espera.setAlignment(QtCore.Qt.AlignCenter)
        self.barra_espera.setTextVisible(True)
        self.barra_espera.setInvertedAppearance(True)
        self.barra_espera.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.barra_espera.setObjectName("barra_espera")
        self.verticalLayout_11.addWidget(self.barra_espera)
        self.mensaje_progreso = QtWidgets.QLabel(self.espera_content)
        self.mensaje_progreso.setStyleSheet("QLabel{\n"
"color: red;\n"
"font-weight: bold;\n"
"font-size: 12px;\n"
"margin-top: 20px;\n"
"}")
        self.mensaje_progreso.setText("")
        self.mensaje_progreso.setAlignment(QtCore.Qt.AlignCenter)
        self.mensaje_progreso.setObjectName("mensaje_progreso")
        self.verticalLayout_11.addWidget(self.mensaje_progreso)
        spacerItem2 = QtWidgets.QSpacerItem(20, 236, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem2)
        self.layout_espera.addWidget(self.espera_content)
        self.paginador.addWidget(self.espera)
        self.inicio = QtWidgets.QWidget()
        self.inicio.setObjectName("inicio")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.inicio)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cont_inicio = QtWidgets.QFrame(self.inicio)
        self.cont_inicio.setStyleSheet("QFrame{\n"
"background-color: #171520;\n"
"\n"
"}\n"
"")
        self.cont_inicio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cont_inicio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cont_inicio.setObjectName("cont_inicio")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.cont_inicio)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titulo_inicio = QtWidgets.QLabel(self.cont_inicio)
        self.titulo_inicio.setMinimumSize(QtCore.QSize(660, 60))
        self.titulo_inicio.setMaximumSize(QtCore.QSize(16777215, 80))
        self.titulo_inicio.setStyleSheet("QLabel{\n"
"color: #F0EDE8;\n"
"    font: 57 18pt \"Outfit Medium\";\n"
"}")
        self.titulo_inicio.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.titulo_inicio.setObjectName("titulo_inicio")
        self.verticalLayout_2.addWidget(self.titulo_inicio)
        self.cont_ini_buts = QtWidgets.QFrame(self.cont_inicio)
        self.cont_ini_buts.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cont_ini_buts.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cont_ini_buts.setObjectName("cont_ini_buts")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.cont_ini_buts)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ini_polo_liso = QtWidgets.QToolButton(self.cont_ini_buts)
        self.ini_polo_liso.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ini_polo_liso.setFont(font)
        self.ini_polo_liso.setStyleSheet("QToolButton{\n"
"background-color: rgb(223, 223, 223);\n"
"border-radius: 15px;\n"
"padding: 10px;\n"
"}\n"
"\n"
"QToolButton:pressed{\n"
"background-color: rgb(171, 171, 171);\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-color: beige;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../img/Polo liso.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ini_polo_liso.setIcon(icon2)
        self.ini_polo_liso.setIconSize(QtCore.QSize(200, 200))
        self.ini_polo_liso.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.ini_polo_liso.setObjectName("ini_polo_liso")
        self.horizontalLayout.addWidget(self.ini_polo_liso)
        self.ini_polo_saliente = QtWidgets.QToolButton(self.cont_ini_buts)
        self.ini_polo_saliente.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ini_polo_saliente.setFont(font)
        self.ini_polo_saliente.setStyleSheet("QToolButton{\n"
"background-color: rgb(223, 223, 223);\n"
"border-radius: 15px;\n"
"padding: 10px;\n"
"}\n"
"\n"
"QToolButton:pressed{\n"
"background-color: rgb(171, 171, 171);\n"
"border-style: outset;\n"
"border-width: 3px;\n"
"border-color: beige;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../img/Polo saliente.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ini_polo_saliente.setIcon(icon3)
        self.ini_polo_saliente.setIconSize(QtCore.QSize(200, 200))
        self.ini_polo_saliente.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.ini_polo_saliente.setObjectName("ini_polo_saliente")
        self.horizontalLayout.addWidget(self.ini_polo_saliente)
        self.verticalLayout_2.addWidget(self.cont_ini_buts)
        self.verticalLayout.addWidget(self.cont_inicio)
        self.paginador.addWidget(self.inicio)
        self.polo_liso = QtWidgets.QWidget()
        self.polo_liso.setObjectName("polo_liso")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.polo_liso)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cont_liso = QtWidgets.QFrame(self.polo_liso)
        self.cont_liso.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cont_liso.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cont_liso.setObjectName("cont_liso")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.cont_liso)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.liso_titulo_1 = QtWidgets.QLabel(self.cont_liso)
        self.liso_titulo_1.setMinimumSize(QtCore.QSize(0, 30))
        self.liso_titulo_1.setMaximumSize(QtCore.QSize(16777215, 60))
        self.liso_titulo_1.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 24px;\n"
"}")
        self.liso_titulo_1.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.liso_titulo_1.setObjectName("liso_titulo_1")
        self.verticalLayout_5.addWidget(self.liso_titulo_1)
        self.liso_titulo_2 = QtWidgets.QLabel(self.cont_liso)
        self.liso_titulo_2.setMinimumSize(QtCore.QSize(0, 30))
        self.liso_titulo_2.setMaximumSize(QtCore.QSize(16777215, 35))
        self.liso_titulo_2.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"font-size: 16px;\n"
"}")
        self.liso_titulo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.liso_titulo_2.setObjectName("liso_titulo_2")
        self.verticalLayout_5.addWidget(self.liso_titulo_2)
        self.liso_inputs = QtWidgets.QFrame(self.cont_liso)
        self.liso_inputs.setStyleSheet("")
        self.liso_inputs.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.liso_inputs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.liso_inputs.setObjectName("liso_inputs")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.liso_inputs)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.liso_input_content = QtWidgets.QFrame(self.liso_inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.liso_input_content.sizePolicy().hasHeightForWidth())
        self.liso_input_content.setSizePolicy(sizePolicy)
        self.liso_input_content.setMinimumSize(QtCore.QSize(700, 350))
        self.liso_input_content.setMaximumSize(QtCore.QSize(900, 420))
        self.liso_input_content.setStyleSheet("QFrame{\n"
"background-color: rgb(217, 217, 217);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-color: black;\n"
"border-width: 2px;\n"
"}")
        self.liso_input_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.liso_input_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.liso_input_content.setObjectName("liso_input_content")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.liso_input_content)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.input_left = QtWidgets.QFrame(self.liso_input_content)
        self.input_left.setStyleSheet("QFrame{\n"
"background-color: rgb(217, 217, 217);\n"
"border-style: none;\n"
"}")
        self.input_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_left.setObjectName("input_left")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.input_left)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_19 = QtWidgets.QFrame(self.input_left)
        self.frame_19.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.liso_p_aparente = QtWidgets.QLineEdit(self.frame_19)
        self.liso_p_aparente.setMaximumSize(QtCore.QSize(100, 16777215))
        self.liso_p_aparente.setStyleSheet("QLineEdit{\n"
"background-color: rgb(243, 238, 238);\n"
"border-radius: 2px;\n"
"border: 1px solid gray;\n"
"}")
        self.liso_p_aparente.setObjectName("liso_p_aparente")
        self.horizontalLayout_11.addWidget(self.liso_p_aparente)
        self.liso_p_aparente_label = QtWidgets.QLabel(self.frame_19)
        self.liso_p_aparente_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.liso_p_aparente_label.setStyleSheet("QLabel{\n"
"color: rgb(53, 53, 53);\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"}")
        self.liso_p_aparente_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.liso_p_aparente_label.setObjectName("liso_p_aparente_label")
        self.horizontalLayout_11.addWidget(self.liso_p_aparente_label)
        self.verticalLayout_10.addWidget(self.frame_19)
        self.frame_20 = QtWidgets.QFrame(self.input_left)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.liso_f_p = QtWidgets.QLineEdit(self.frame_20)
        self.liso_f_p.setMaximumSize(QtCore.QSize(100, 16777215))
        self.liso_f_p.setStyleSheet("QLineEdit{\n"
"background-color: rgb(243, 238, 238);\n"
"border-radius: 2px;\n"
"border: 1px solid gray;\n"
"}")
        self.liso_f_p.setObjectName("liso_f_p")
        self.horizontalLayout_12.addWidget(self.liso_f_p)
        self.liso_f_p_label = QtWidgets.QLabel(self.frame_20)
        self.liso_f_p_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.liso_f_p_label.setStyleSheet("QLabel{\n"
"color: rgb(53, 53, 53);\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"}")
        self.liso_f_p_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.liso_f_p_label.setObjectName("liso_f_p_label")
        self.horizontalLayout_12.addWidget(self.liso_f_p_label)
        self.verticalLayout_10.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.input_left)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.liso_t_m_c = QtWidgets.QLineEdit(self.frame_21)
        self.liso_t_m_c.setMaximumSize(QtCore.QSize(100, 16777215))
        self.liso_t_m_c.setStyleSheet("QLineEdit{\n"
"background-color: rgb(243, 238, 238);\n"
"border-radius: 2px;\n"
"border: 1px solid gray;\n"
"}")
        self.liso_t_m_c.setObjectName("liso_t_m_c")
        self.horizontalLayout_13.addWidget(self.liso_t_m_c)
        self.liso_t_m_c_label = QtWidgets.QLabel(self.frame_21)
        self.liso_t_m_c_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.liso_t_m_c_label.setStyleSheet("QLabel{\n"
"color: rgb(53, 53, 53);\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"}")
        self.liso_t_m_c_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.liso_t_m_c_label.setObjectName("liso_t_m_c_label")
        self.horizontalLayout_13.addWidget(self.liso_t_m_c_label)
        self.verticalLayout_10.addWidget(self.frame_21)
        self.frame_23 = QtWidgets.QFrame(self.input_left)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.liso_estabilidad_practica = QtWidgets.QLineEdit(self.frame_23)
        self.liso_estabilidad_practica.setMaximumSize(QtCore.QSize(100, 16777215))
        self.liso_estabilidad_practica.setStyleSheet("QLineEdit{\n"
"background-color: rgb(243, 238, 238);\n"
"border-radius: 2px;\n"
"border: 1px solid gray;\n"
"}")
        self.liso_estabilidad_practica.setObjectName("liso_estabilidad_practica")
        self.horizontalLayout_14.addWidget(self.liso_estabilidad_practica)
        self.liso_estabilidad_practica_label = QtWidgets.QLabel(self.frame_23)
        self.liso_estabilidad_practica_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.liso_estabilidad_practica_label.setStyleSheet("QLabel{\n"
"color: rgb(53, 53, 53);\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"}")
        self.liso_estabilidad_practica_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.liso_estabilidad_practica_label.setObjectName("liso_estabilidad_practica_label")
        self.horizontalLayout_14.addWidget(self.liso_estabilidad_practica_label)
        self.verticalLayout_10.addWidget(self.frame_23)
        self.liso_pu_check = QtWidgets.QCheckBox(self.input_left)
        self.liso_pu_check.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.liso_pu_check.setStyleSheet("QCheckBox{\n"
"background-color: rgb(217, 217, 217);\n"
"color: rgb(53, 53, 53);\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"}")
        self.liso_pu_check.setObjectName("liso_pu_check")
        self.verticalLayout_10.addWidget(self.liso_pu_check)
        self.horizontalLayout_5.addWidget(self.input_left)
        self.input_right = QtWidgets.QFrame(self.liso_input_content)
        self.input_right.setStyleSheet("QFrame{\n"
"background-color: rgb(217, 217, 217);\n"
"border-style: none;\n"
"}")
        self.input_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_right.setObjectName("input_right")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.input_right)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.cont_voltaje_nom = QtWidgets.QFrame(self.input_right)
        self.cont_voltaje_nom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cont_voltaje_nom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cont_voltaje_nom.setObjectName("cont_voltaje_nom")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.cont_voltaje_nom)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.voltaje_nominal = QtWidgets.QComboBox(self.cont_voltaje_nom)
        self.voltaje_nominal.setMinimumSize(QtCore.QSize(101, 0))
        self.voltaje_nominal.setMaximumSize(QtCore.QSize(100, 16777215))
        self.voltaje_nominal.setStyleSheet("QComboBox{\n"
"background-color: rgb(243, 238, 238);\n"
"border: 1px solid gray;\n"
"border-radius: 3px;\n"
"padding: 1px 18px 1px 3px;\n"
"min-width: 6em;\n"
"}\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"QScrollBar:vertical {          \n"
"    border-style: solid;\n"
"    background: rgb(243, 238, 238);\n"
"    width:15px;\n"
"}\n"
"")
        self.voltaje_nominal.setObjectName("voltaje_nominal")
        self.voltaje_nominal.addItem("")
        self.voltaje_nominal.addItem("")
        self.voltaje_nominal.addItem("")
        self.voltaje_nominal.addItem("")
        self.voltaje_nominal.addItem("")
        self.voltaje_nominal.addItem("")
        self.voltaje_nominal.addItem("")
        self.voltaje_nominal.addItem("")
        self.voltaje_nominal.addItem("")
        self.voltaje_nominal.addItem("")
        self.voltaje_nominal.addItem("")
        self.voltaje_nominal.addItem("")
        self.horizontalLayout_6.addWidget(self.voltaje_nominal)
        self.liso_v_n_label = QtWidgets.QLabel(self.cont_voltaje_nom)
        self.liso_v_n_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.liso_v_n_label.setStyleSheet("QLabel{\n"
"color: rgb(53, 53, 53);\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"}")
        self.liso_v_n_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.liso_v_n_label.setObjectName("liso_v_n_label")
        self.horizontalLayout_6.addWidget(self.liso_v_n_label)
        self.verticalLayout_9.addWidget(self.cont_voltaje_nom)
        self.cont_r_s = QtWidgets.QFrame(self.input_right)
        self.cont_r_s.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cont_r_s.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cont_r_s.setObjectName("cont_r_s")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.cont_r_s)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.liso_r_s = QtWidgets.QLineEdit(self.cont_r_s)
        self.liso_r_s.setMaximumSize(QtCore.QSize(100, 16777215))
        self.liso_r_s.setStyleSheet("QLineEdit{\n"
"background-color: rgb(243, 238, 238);\n"
"border-radius: 2px;\n"
"border: 1px solid gray;\n"
"}")
        self.liso_r_s.setObjectName("liso_r_s")
        self.horizontalLayout_7.addWidget(self.liso_r_s)
        self.liso_r_s_label = QtWidgets.QLabel(self.cont_r_s)
        self.liso_r_s_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.liso_r_s_label.setStyleSheet("QLabel{\n"
"color: rgb(53, 53, 53);\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"}")
        self.liso_r_s_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.liso_r_s_label.setObjectName("liso_r_s_label")
        self.horizontalLayout_7.addWidget(self.liso_r_s_label)
        self.verticalLayout_9.addWidget(self.cont_r_s)
        self.cont_p_m = QtWidgets.QFrame(self.input_right)
        self.cont_p_m.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cont_p_m.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cont_p_m.setObjectName("cont_p_m")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.cont_p_m)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.liso_p_m = QtWidgets.QLineEdit(self.cont_p_m)
        self.liso_p_m.setMaximumSize(QtCore.QSize(100, 16777215))
        self.liso_p_m.setStyleSheet("QLineEdit{\n"
"background-color: rgb(243, 238, 238);\n"
"border-radius: 2px;\n"
"border: 1px solid gray;\n"
"}")
        self.liso_p_m.setObjectName("liso_p_m")
        self.horizontalLayout_3.addWidget(self.liso_p_m)
        self.liso_p_m_label = QtWidgets.QLabel(self.cont_p_m)
        self.liso_p_m_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.liso_p_m_label.setStyleSheet("QLabel{\n"
"color: rgb(53, 53, 53);\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"}")
        self.liso_p_m_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.liso_p_m_label.setObjectName("liso_p_m_label")
        self.horizontalLayout_3.addWidget(self.liso_p_m_label)
        self.verticalLayout_9.addWidget(self.cont_p_m)
        self.cont_seg_max = QtWidgets.QFrame(self.input_right)
        self.cont_seg_max.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cont_seg_max.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cont_seg_max.setObjectName("cont_seg_max")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.cont_seg_max)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.liso_porcentaje_seg = QtWidgets.QComboBox(self.cont_seg_max)
        self.liso_porcentaje_seg.setMinimumSize(QtCore.QSize(101, 0))
        self.liso_porcentaje_seg.setMaximumSize(QtCore.QSize(100, 16777215))
        self.liso_porcentaje_seg.setStyleSheet("QComboBox{\n"
"background-color: rgb(243, 238, 238);\n"
"border: 1px solid gray;\n"
"border-radius: 3px;\n"
"padding: 1px 18px 1px 3px;\n"
"min-width: 6em;\n"
"}\n"
"QComboBox:editable {\n"
"    background: white;\n"
"}\n"
"QScrollBar:vertical {          \n"
"    border-style: solid;\n"
"    background: rgb(243, 238, 238);\n"
"    width:15px;\n"
"}")
        self.liso_porcentaje_seg.setObjectName("liso_porcentaje_seg")
        self.liso_porcentaje_seg.addItem("")
        self.liso_porcentaje_seg.addItem("")
        self.liso_porcentaje_seg.addItem("")
        self.liso_porcentaje_seg.addItem("")
        self.liso_porcentaje_seg.addItem("")
        self.horizontalLayout_8.addWidget(self.liso_porcentaje_seg)
        self.liso_porcentaj_seg_label = QtWidgets.QLabel(self.cont_seg_max)
        self.liso_porcentaj_seg_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.liso_porcentaj_seg_label.setStyleSheet("QLabel{\n"
"color: rgb(53, 53, 53);\n"
"font-weight: bold;\n"
"font-size: 14px;\n"
"}")
        self.liso_porcentaj_seg_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.liso_porcentaj_seg_label.setObjectName("liso_porcentaj_seg_label")
        self.horizontalLayout_8.addWidget(self.liso_porcentaj_seg_label)
        self.verticalLayout_9.addWidget(self.cont_seg_max)
        self.horizontalLayout_5.addWidget(self.input_right)
        self.horizontalLayout_4.addWidget(self.liso_input_content)
        self.verticalLayout_5.addWidget(self.liso_inputs)
        self.liso_campos = QtWidgets.QLabel(self.cont_liso)
        self.liso_campos.setMinimumSize(QtCore.QSize(0, 30))
        self.liso_campos.setMaximumSize(QtCore.QSize(16777215, 25))
        self.liso_campos.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"font-size: 14px;\n"
"}")
        self.liso_campos.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.liso_campos.setObjectName("liso_campos")
        self.verticalLayout_5.addWidget(self.liso_campos)
        self.liso_error_mess = QtWidgets.QLabel(self.cont_liso)
        self.liso_error_mess.setMinimumSize(QtCore.QSize(0, 30))
        self.liso_error_mess.setMaximumSize(QtCore.QSize(16777215, 25))
        self.liso_error_mess.setStyleSheet("QLabel{\n"
"color: red;\n"
"}")
        self.liso_error_mess.setText("")
        self.liso_error_mess.setAlignment(QtCore.Qt.AlignCenter)
        self.liso_error_mess.setObjectName("liso_error_mess")
        self.verticalLayout_5.addWidget(self.liso_error_mess)
        self.liso_content_but = QtWidgets.QFrame(self.cont_liso)
        self.liso_content_but.setMinimumSize(QtCore.QSize(0, 50))
        self.liso_content_but.setMaximumSize(QtCore.QSize(16777215, 50))
        self.liso_content_but.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.liso_content_but.setFrameShadow(QtWidgets.QFrame.Raised)
        self.liso_content_but.setObjectName("liso_content_but")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.liso_content_but)
        self.horizontalLayout_2.setContentsMargins(40, 0, 40, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.liso_graficar = QtWidgets.QPushButton(self.liso_content_but)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.liso_graficar.setFont(font)
        self.liso_graficar.setStyleSheet("QPushButton{\n"
"background-color: rgb(194, 221, 245);\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(143, 163, 188, 245);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-color: beige;\n"
"color: white;\n"
"}")
        self.liso_graficar.setIcon(icon)
        self.liso_graficar.setIconSize(QtCore.QSize(0, 0))
        self.liso_graficar.setObjectName("liso_graficar")
        self.horizontalLayout_2.addWidget(self.liso_graficar)
        spacerItem3 = QtWidgets.QSpacerItem(470, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.liso_anterior = QtWidgets.QPushButton(self.liso_content_but)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.liso_anterior.setFont(font)
        self.liso_anterior.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.liso_anterior.setStyleSheet("QPushButton{\n"
"background-color: rgb(194, 221, 245);\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(143, 163, 188, 245);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-color: beige;\n"
"color: white;\n"
"}")
        self.liso_anterior.setIcon(icon1)
        self.liso_anterior.setIconSize(QtCore.QSize(0, 0))
        self.liso_anterior.setObjectName("liso_anterior")
        self.horizontalLayout_2.addWidget(self.liso_anterior)
        self.verticalLayout_5.addWidget(self.liso_content_but)
        self.verticalLayout_4.addWidget(self.cont_liso)
        self.paginador.addWidget(self.polo_liso)
        self.curva = QtWidgets.QWidget()
        self.curva.setObjectName("curva")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.curva)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.curva_content = QtWidgets.QFrame(self.curva)
        self.curva_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.curva_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.curva_content.setObjectName("curva_content")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.curva_content)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.curva_content)
        self.label.setMaximumSize(QtCore.QSize(16777215, 80))
        self.label.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 24px;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.plot_content = QtWidgets.QFrame(self.curva_content)
        self.plot_content.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.plot_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plot_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plot_content.setObjectName("plot_content")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.plot_content)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.plot_canvas = QtWidgets.QWidget(self.plot_content)
        self.plot_canvas.setMaximumSize(QtCore.QSize(900, 500))
        self.plot_canvas.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.plot_canvas.setObjectName("plot_canvas")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.plot_canvas)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_17.addWidget(self.plot_canvas)
        self.verticalLayout_3.addWidget(self.plot_content)
        self.curva_butt_content = QtWidgets.QFrame(self.curva_content)
        self.curva_butt_content.setMaximumSize(QtCore.QSize(16777215, 50))
        self.curva_butt_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.curva_butt_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.curva_butt_content.setObjectName("curva_butt_content")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.curva_butt_content)
        self.horizontalLayout_15.setContentsMargins(40, 0, 40, 5)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.inicio_plot = QtWidgets.QPushButton(self.curva_butt_content)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.inicio_plot.setFont(font)
        self.inicio_plot.setStyleSheet("QPushButton{\n"
"background-color: rgb(194, 221, 245);\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: black;\n"
"padding: 5px;\n"
"}")
        self.inicio_plot.setIcon(icon)
        self.inicio_plot.setObjectName("inicio_plot")
        self.horizontalLayout_15.addWidget(self.inicio_plot)
        spacerItem4 = QtWidgets.QSpacerItem(489, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.anterior_plot = QtWidgets.QPushButton(self.curva_butt_content)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.anterior_plot.setFont(font)
        self.anterior_plot.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.anterior_plot.setStyleSheet("QPushButton{\n"
"background-color: rgb(194, 221, 245);\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: black;\n"
"padding: 5px;\n"
"}")
        self.anterior_plot.setIcon(icon1)
        self.anterior_plot.setIconSize(QtCore.QSize(14, 14))
        self.anterior_plot.setObjectName("anterior_plot")
        self.horizontalLayout_15.addWidget(self.anterior_plot)
        self.verticalLayout_3.addWidget(self.curva_butt_content)
        self.verticalLayout_6.addWidget(self.curva_content)
        self.paginador.addWidget(self.curva)
        self.verticalLayout_7.addWidget(self.paginador)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.paginador.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GUI lite V1.0"))
        self.saliente_titulo_1.setText(_translate("MainWindow", "Graficar curva de capacidad "))
        self.saliente_titulo.setText(_translate("MainWindow", "Ingrese datos para un generador de polos salientes"))
        self.sal_p_aparente_label.setText(_translate("MainWindow", "Potencia aparente**"))
        self.sal_f_p_label.setText(_translate("MainWindow", "Factor de potencia**"))
        self.sal_t_m_c_label.setText(_translate("MainWindow", "Tensión de campo máxima"))
        self.sal_estabilidad_practica_label.setText(_translate("MainWindow", "Estabilidad práctica**"))
        self.saliente_pu_check.setText(_translate("MainWindow", "Valores en P.U."))
        self.sal_r_q_label.setText(_translate("MainWindow", "Reactancia cuadratura**"))
        self.voltaje_nominal_sal.setItemText(0, _translate("MainWindow", "240"))
        self.voltaje_nominal_sal.setItemText(1, _translate("MainWindow", "480"))
        self.voltaje_nominal_sal.setItemText(2, _translate("MainWindow", "600"))
        self.voltaje_nominal_sal.setItemText(3, _translate("MainWindow", "2400"))
        self.voltaje_nominal_sal.setItemText(4, _translate("MainWindow", "4160"))
        self.voltaje_nominal_sal.setItemText(5, _translate("MainWindow", "4800"))
        self.voltaje_nominal_sal.setItemText(6, _translate("MainWindow", "6900"))
        self.voltaje_nominal_sal.setItemText(7, _translate("MainWindow", "13800"))
        self.voltaje_nominal_sal.setItemText(8, _translate("MainWindow", "23000"))
        self.voltaje_nominal_sal.setItemText(9, _translate("MainWindow", "34500"))
        self.voltaje_nominal_sal.setItemText(10, _translate("MainWindow", "46000"))
        self.voltaje_nominal_sal.setItemText(11, _translate("MainWindow", "69000"))
        self.sal_v_n_label.setText(_translate("MainWindow", "Voltaje nominal**"))
        self.sal_r_d_label.setText(_translate("MainWindow", "Reactancia directa**"))
        self.sal_p_m_label.setText(_translate("MainWindow", "Potencia motriz máxima"))
        self.sal_porcentaje_seg.setItemText(0, _translate("MainWindow", "2"))
        self.sal_porcentaje_seg.setItemText(1, _translate("MainWindow", "5"))
        self.sal_porcentaje_seg.setItemText(2, _translate("MainWindow", "10"))
        self.sal_porcentaje_seg.setItemText(3, _translate("MainWindow", "12"))
        self.sal_porcentaje_seg.setItemText(4, _translate("MainWindow", "15"))
        self.sal_porcentaj_seg_label.setText(_translate("MainWindow", "Porcentaje de seguridad**"))
        self.saliente_campos.setText(_translate("MainWindow", "Los campos indicados con ** son obligatorios."))
        self.saliente_graficar.setText(_translate("MainWindow", "Graficar"))
        self.saliente_anterior.setText(_translate("MainWindow", "Anterior"))
        self.label_2.setText(_translate("MainWindow", "Generando curva de capacidad"))
        self.titulo_inicio.setText(_translate("MainWindow", "Graficar curva de capacidad - Seleccione el tipo de generador"))
        self.ini_polo_liso.setText(_translate("MainWindow", "Polos lisos"))
        self.ini_polo_saliente.setText(_translate("MainWindow", "Polos salientes"))
        self.liso_titulo_1.setText(_translate("MainWindow", "Graficar curva de capacidad "))
        self.liso_titulo_2.setText(_translate("MainWindow", "Ingrese datos para un generador de polos lisos"))
        self.liso_p_aparente_label.setText(_translate("MainWindow", "Potencia aparente**"))
        self.liso_f_p_label.setText(_translate("MainWindow", "Factor de potencia**"))
        self.liso_t_m_c_label.setText(_translate("MainWindow", "Tensión de campo máxima"))
        self.liso_estabilidad_practica_label.setText(_translate("MainWindow", "Estabilidad práctica**"))
        self.liso_pu_check.setText(_translate("MainWindow", "Valores en P.U."))
        self.voltaje_nominal.setItemText(0, _translate("MainWindow", "240"))
        self.voltaje_nominal.setItemText(1, _translate("MainWindow", "480"))
        self.voltaje_nominal.setItemText(2, _translate("MainWindow", "600"))
        self.voltaje_nominal.setItemText(3, _translate("MainWindow", "2400"))
        self.voltaje_nominal.setItemText(4, _translate("MainWindow", "4160"))
        self.voltaje_nominal.setItemText(5, _translate("MainWindow", "4800"))
        self.voltaje_nominal.setItemText(6, _translate("MainWindow", "6900"))
        self.voltaje_nominal.setItemText(7, _translate("MainWindow", "13800"))
        self.voltaje_nominal.setItemText(8, _translate("MainWindow", "23000"))
        self.voltaje_nominal.setItemText(9, _translate("MainWindow", "34500"))
        self.voltaje_nominal.setItemText(10, _translate("MainWindow", "46000"))
        self.voltaje_nominal.setItemText(11, _translate("MainWindow", "69000"))
        self.liso_v_n_label.setText(_translate("MainWindow", "Voltaje nominal**"))
        self.liso_r_s_label.setText(_translate("MainWindow", "Reactancia sincrónica**"))
        self.liso_p_m_label.setText(_translate("MainWindow", "Potencia motriz máxima"))
        self.liso_porcentaje_seg.setItemText(0, _translate("MainWindow", "2"))
        self.liso_porcentaje_seg.setItemText(1, _translate("MainWindow", "5"))
        self.liso_porcentaje_seg.setItemText(2, _translate("MainWindow", "10"))
        self.liso_porcentaje_seg.setItemText(3, _translate("MainWindow", "12"))
        self.liso_porcentaje_seg.setItemText(4, _translate("MainWindow", "15"))
        self.liso_porcentaj_seg_label.setText(_translate("MainWindow", "Porcentaje de seguridad**"))
        self.liso_campos.setText(_translate("MainWindow", "Los campos indicados con ** son obligatorios."))
        self.liso_graficar.setText(_translate("MainWindow", "Graficar"))
        self.liso_anterior.setText(_translate("MainWindow", "Anterior"))
        self.label.setText(_translate("MainWindow", "Graficar curva de capacidad - Generador de polos lisos "))
        self.inicio_plot.setText(_translate("MainWindow", "Inicio"))
        self.anterior_plot.setText(_translate("MainWindow", "Anterior"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
